name: 'GitHub Action for Clickhouse Server'
description: 'Configure and start Clickhouse Server'

branding:
  icon: 'database'
  color: 'yellow'

runs:
  steps:
  - name: Set up Clikhouse
    run: |
        sudo apt-get install -y apt-transport-https ca-certificates dirmngr
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
        echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee \
            /etc/apt/sources.list.d/clickhouse.list
        sudo apt-get update
        sudo apt-get install -y clickhouse-server clickhouse-client
        sudo service clickhouse-server start
        sudo clickhouse-client --query "CREATE DATABASE IF NOT EXISTS test"
        sudo clickhouse-client --query "CREATE TABLE IF NOT EXISTS test.test (Subject String, CreateDateTime DateTime, Content String) ENGINE = Memory"
        sudo clickhouse-client --query "INSERT INTO test.test VALUES ('test', now(), 'test')"
        sudo clickhouse-client --query "SELECT * FROM test.test"

  - name: Create database objects
    run: |
        sudo clickhouse-client --query "CREATE DATABASE IF NOT EXISTS test"
        sudo clickhouse-client --query "CREATE TABLE IF NOT EXISTS test.test (Subject String, CreateDateTime DateTime, Content String) ENGINE = Memory"
        sudo clickhouse-client --query "INSERT INTO test.test VALUES ('test', now(), 'test')"

  - name: Check Clickhouse
    run: |
      sudo clickhouse-client --query "SELECT * FROM test.test"